In [1]:
import numpy as np

In [3]:
a = np.random.randint(30,99,(7,8))
a

array([[84, 72, 74, 42, 50, 58, 65, 35],
       [72, 46, 36, 68, 55, 87, 32, 43],
       [78, 95, 42, 80, 70, 67, 85, 74],
       [98, 40, 61, 31, 36, 51, 36, 48],
       [41, 84, 67, 34, 48, 50, 88, 51],
       [49, 58, 78, 82, 88, 89, 45, 40],
       [77, 83, 75, 64, 64, 56, 96, 73]])

In [7]:
a = np.random.randint(30,99,20)
a


array([71, 88, 54, 73, 51, 92, 82, 36, 85, 69, 33, 62, 71, 49, 54, 49, 61,
       41, 81, 79])

In [9]:
a[0]

71

In [11]:
a[-1]

79

In [13]:
a[4]

51

In [16]:
a.ndim

1

In [26]:
b = np.random.randint(20,80,(8,9))
b

array([[66, 54, 53, 30, 43, 53, 65, 78, 67],
       [23, 42, 49, 42, 31, 46, 57, 32, 25],
       [52, 42, 22, 60, 78, 49, 43, 23, 27],
       [55, 32, 69, 35, 26, 23, 69, 27, 63],
       [71, 43, 76, 27, 52, 27, 36, 57, 57],
       [21, 55, 63, 34, 59, 27, 48, 77, 21],
       [35, 56, 34, 42, 36, 41, 44, 69, 34],
       [24, 78, 71, 48, 45, 52, 76, 65, 66]])

In [28]:
b.shape

(8, 9)

In [30]:
b.ndim

2

In [32]:
b[2:6]

array([[52, 42, 22, 60, 78, 49, 43, 23, 27],
       [55, 32, 69, 35, 26, 23, 69, 27, 63],
       [71, 43, 76, 27, 52, 27, 36, 57, 57],
       [21, 55, 63, 34, 59, 27, 48, 77, 21]])

In [34]:
b[7,0]

24

In [36]:
b[2:6,1:7]

array([[42, 22, 60, 78, 49, 43],
       [32, 69, 35, 26, 23, 69],
       [43, 76, 27, 52, 27, 36],
       [55, 63, 34, 59, 27, 48]])

In [38]:
b[2:6:1,1:7:1]

array([[42, 22, 60, 78, 49, 43],
       [32, 69, 35, 26, 23, 69],
       [43, 76, 27, 52, 27, 36],
       [55, 63, 34, 59, 27, 48]])

In [40]:
import pandas as pd

In [42]:
pd.Series()

Series([], dtype: object)

In [46]:
pd.DataFrame

pandas.core.frame.DataFrame

In [48]:
k = [2,3,4,6,7,8,9,1]
k

[2, 3, 4, 6, 7, 8, 9, 1]

In [50]:
pd.Series(k)

0    2
1    3
2    4
3    6
4    7
5    8
6    9
7    1
dtype: int64

In [52]:
np.array(k)

array([2, 3, 4, 6, 7, 8, 9, 1])

In [94]:
k=[359,8],[358,9],[357,8.5],[356,9]

In [96]:
k

([359, 8], [358, 9], [357, 8.5], [356, 9])

In [98]:
t=np.array(k)
t

array([[359. ,   8. ],
       [358. ,   9. ],
       [357. ,   8.5],
       [356. ,   9. ]])

In [100]:
t.ndim

2

In [102]:
pd.DataFrame(t)

0    1
0  359.0  8.0
1  358.0  9.0
2  357.0  8.5
3  356.0  9.0

In [108]:
pd.DataFrame(t,columns=['Roll No','CGPA'],index=[1,2,3,4])

Roll No  CGPA
1    359.0   8.0
2    358.0   9.0
3    357.0   8.5
4    356.0   9.0

NameError: name 'df' is not defined