In [1]:
import numpy as np


In [3]:
j =  [4,6,2,8,9]

1) numpy                                    -array operations
2) pandas                                   -Data manipulation and analysis
3) matplotlib and Seaborn                   -Graphics Analysis
4) sklearn                                  -Machine learning algorithms and techinques
5) statsmodels                              -statistical analysis
6)  scipy                                   -statistical analysis


In [6]:
j = [3,4,4,6,7,8,8,6]
j

[3, 4, 4, 6, 7, 8, 8, 6]

In [8]:
d=np.array(j)
d

array([3, 4, 4, 6, 7, 8, 8, 6])

In [10]:
type(d)

numpy.ndarray

In [12]:
type(j)

list

In [14]:
d.shape

(8,)

In [16]:
d.ndim

1

In [18]:
d.size

8

In [20]:
d.shape

(8,)

In [44]:
s = np.array([[4,5,6,8],[3,5,2,4],[3,4,6,8],[9,7,5,4],[7,5,4,3]])
s

array([[4, 5, 6, 8],
       [3, 5, 2, 4],
       [3, 4, 6, 8],
       [9, 7, 5, 4],
       [7, 5, 4, 3]])

In [46]:
type(s)

numpy.ndarray

In [50]:
s.shape


(5, 4)

In [52]:
s.size

20

In [62]:
s.ndim

2

In [68]:
arr = np.array([4,6,3,7,5,0])
arr

array([4, 6, 3, 7, 5, 0])

In [70]:
arr.reshape(2,3)

array([[4, 6, 3],
       [7, 5, 0]])

In [72]:
arr.ndim


1

In [80]:
b=s.reshape(2,2,5)

In [82]:
b

array([[[4, 5, 6, 8, 3],
        [5, 2, 4, 3, 4]],

       [[6, 8, 9, 7, 5],
        [4, 7, 5, 4, 3]]])

In [84]:
b.size

20

In [98]:
b.reshape(10,2)


array([[4, 5],
       [6, 8],
       [3, 5],
       [2, 4],
       [3, 4],
       [6, 8],
       [9, 7],
       [5, 4],
       [7, 5],
       [4, 3]])

In [100]:
b.ndim

3

In [102]:
list(range(0,1001,100))


[0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]

In [104]:
list(range(-1000,1,100))

[-1000, -900, -800, -700, -600, -500, -400, -300, -200, -100, 0]

In [106]:
range(5,20)

range(5, 20)

In [108]:
m=[3,4,5,6,7]
m

[3, 4, 5, 6, 7]

In [110]:
range(3,101)

range(3, 101)

In [112]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [114]:
tuple(range(3,13,2))


(3, 5, 7, 9, 11)

In [116]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [118]:
list(range(10,-10,-2))


[10, 8, 6, 4, 2, 0, -2, -4, -6, -8]

In [122]:
np.arange(2.5,5,0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [124]:
range(5,50,5)

range(5, 50, 5)

In [126]:
for i in range(5,50,5):
    print('Data',i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [134]:
j = [3,40,58,35,75,94,94,9,56,84]
j

[3, 40, 58, 35, 75, 94, 94, 9, 56, 84]

In [138]:
j[0:11:1]

[3, 40, 58, 35, 75, 94, 94, 9, 56, 84]

In [140]:
j[0:11:2]

[3, 58, 75, 94, 56]

In [142]:
x=[]
y=[]
for i in range(len(j)):
    if i %2==0:
        x.append(j[i]
